#!/usr/bin/env python3
"""The cost tables, typeset from the measurements and never retyped.

Reads ``data/metrics/cost.json`` (parameters, per-query timing, per-building
featurisation; written by ``measure_cost.py``) and ``data/metrics/render_cost.json``
(the candidate-grid render times, read from the logs of the runs that produced
the grids in use) and writes the same tables as LaTeX and as Markdown:

    tables/compute_cost.tex     four booktabs tables, \\input-able
    tables/compute_cost.md      the same, for reading

    /opt/conda/envs/shared_audio/bin/python src/make_cost_table.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
HERE = Path(__file__).resolve().parents[1]
DATA = HERE / "data"

TABLES = HERE / "tables"
SCENES = ["office_4", "apartment_2", "frl_apartment_5"]
STAGES = [
    ("image_io", "image read and normalisation", "CPU", "(f)"),
    ("vis_encoder", "UnLoc encoder, 640$\\times$480", "GPU", "(f)"),
    ("vis_rays", "ray extraction from predicted depth", "CPU", "(b)"),
    ("vis_localize", "match against the pose grid, 36 headings", "GPU", "(b)"),
    ("ac_io", "impulse response read, 6 ch at 48 kHz", "CPU", "(b)"),
    ("ac_feature", "banded STFT of the recording", "CPU", "(b)"),
    ("ac_score", "score every candidate cell", "CPU", "(b)"),
    ("modes", "ten hypotheses and their disc evidence", "CPU", "(b)"),
    ("fusion", "gated fusion", "CPU", "(b)"),
]


def esc(s: str) -> str:
    return s.replace("_", "\\_")


def gb(b: float) -> str:
    return f"{b / 1e9:.2f}"


def mb(b: float) -> str:
    return f"{b / 1e6:.1f}"


def main() -> int:
    cost = json.loads((DATA / "cost.json").read_text())
    render = json.loads((DATA / "render_cost.json").read_text())["results"]
    hw = cost["hardware"]
    tex: list[str] = []
    md: list[str] = []
    T, M = tex.append, md.append

    T("% Generated by analysis/exp1_computational_resource/src/make_cost_table.py from data/cost.json "
      "and data/render_cost.json. Do not edit by hand.")
    md_hw = (f"Measured on one {hw['gpu']} and a {hw['cpu']}, PyTorch {hw['torch']}. "
             f"Per-query times are medians over {cost['online']['n_queries_per_scene']} "
             f"held-out queries per scene after warm-up.")
    M("# Computational cost\n")
    M(md_hw + "\n")
    legend = ("(f) front branch: the image encoder, which the acoustic branch does not "
              "touch. (b) back branch: everything after it, the ray head, the floorplan "
              "match, and the acoustic term and fusion that join there.")
    M(legend + "\n")
    T(r"\noindent\footnotesize " + legend)
    T("")

    # ------------------------------------------------------------ parameters
    T(r"\begin{table}[t]\centering\small")
    T(r"\caption{Parameters by branch. The acoustic branch is a matcher with no "
      r"weights beyond one linear projection, and the fusion rule is three scalars chosen on "
      r"validation rooms; everything it touches is in the (b) rows, "
      r"and the (b) rows are 2 to 9\% of each backbone.}")
    T(r"\label{tab:params}")
    T(r"\begin{tabular}{llrl}\toprule")
    T(r"Component & Branch & Parameters & Note \\\midrule")
    M("## Learned parameters\n")
    M("| component | branch | parameters | note |")
    M("|---|---|---|---|")
    bb_params = {}
    for tag in ("unloc", "f3loc_mono", "disco_rrp"):
        f = DATA / f"backbone_{tag}.json"
        if f.exists():
            bb_params[tag] = json.loads(f.read_text())
    enc_note = {"UnLoc": "ViT-L, frozen", "F3Loc mono": "ResNet-50, layer 1",
                "DisCo-FLoc RRP": "ViT-S, frozen"}
    head_note = "conv and attention that turn features into rays"
    for tag, d in bb_params.items():
        lab, pr = d["label"], d["params"]
        T(rf"{esc(lab)} encoder & (f) & {pr['encoder']/1e6:.1f} M & {enc_note.get(lab, '')} \\")
        T(rf"{esc(lab)} head & (b) & {pr['head']/1e6:.2f} M & {head_note} \\")
        M(f"| {lab} encoder | (f) | {pr['encoder']/1e6:.1f} M | {enc_note.get(lab, '')} |")
        M(f"| {lab} head | (b) | {pr['head']/1e6:.2f} M | {head_note} |")
        if pr["unused_at_inference"]:
            T(rf"{esc(lab)} depth head & \textendash & {pr['unused_at_inference']/1e6:.1f} M & "
              r"in the checkpoint, never called at inference \\")
            M(f"| {lab} depth head | - | {pr['unused_at_inference']/1e6:.1f} M | in the checkpoint, never called at inference |")
        T(r"\midrule")
    T(r"floorplan match & (b) & 0 & $L_1$ against the DESDF; nothing learned \\")
    T(r"acoustic branch & (b) & 0.22 M & banded STFT, linear projection $1746 \times 128$, $L_1$ match \\")
    T(r"fusion rule & (b) & 3 & weight, sigmoid scale, visual threshold (one scalar for the cell-product rule) \\")
    M("| floorplan match | (b) | 0 | L1 against the DESDF; nothing learned |")
    M("| acoustic branch | (b) | 0.22 M | banded STFT, linear projection 1746x128, L1 match |")
    M("| fusion rule | (b) | 3 | weight, sigmoid scale, visual threshold (one scalar for the cell-product rule) |")
    T(r"\bottomrule\end{tabular}\end{table}")
    T("")

    # --------------------------------------------------------- per building
    T(r"\begin{table}[t]\centering\small")
    T(r"\caption{Cost per building, paid once. The candidate grid is one impulse "
      r"response per reachable cell, rendered on the wall-only mesh at 48\,kHz "
      r"with reflection depth 50 and 20k indirect rays, split over twelve workers. "
      r"Only its feature is kept at inference. Featurisation time is dominated "
      r"by reading the grid from network storage.}")
    T(r"\label{tab:offline}")
    T(r"\begin{tabular}{lrrrrrrr}\toprule")
    T(r"Scene & Cells & Grid & Render wall & Core-h & s / cell & Feature & Featurise \\")
    T(r" & & GB & min & & & MB & s \\\midrule")
    M("\n## Cost per building, paid once\n")
    M("| scene | cells | grid on disk | render wall (12 workers) | core-hours | s per cell | feature kept | featurise |")
    M("|---|---|---|---|---|---|---|---|")
    tot_cells = tot_core = 0.0
    for s in SCENES:
        o, r = cost["offline"][s], render["render"][s]
        spc = r["core_hours"] * 3600 / r["cells"]
        tot_cells += r["cells"]; tot_core += r["core_hours"]
        T(rf"{esc(s)} & {o['cells']} & {gb(o['grid_bytes'])} & {r['wall_min']:.0f} & "
          rf"{r['core_hours']:.1f} & {spc:.1f} & {mb(o['feature_bytes'])} & {o['featurise_s']:.0f} \\")
        M(f"| {s} | {o['cells']} | {gb(o['grid_bytes'])} GB | {r['wall_min']:.0f} min | "
          f"{r['core_hours']:.1f} | {spc:.1f} | {mb(o['feature_bytes'])} MB | {o['featurise_s']:.0f} s |")
    T(r"\midrule")
    T(rf"all three & {int(tot_cells)} & {gb(sum(cost['offline'][s]['grid_bytes'] for s in SCENES))} & "
      rf"& {tot_core:.1f} & {tot_core*3600/tot_cells:.1f} & "
      rf"{mb(sum(cost['offline'][s]['feature_bytes'] for s in SCENES))} & \\")
    T(r"\bottomrule\end{tabular}\end{table}")
    T("")
    M(f"\nAll three: {int(tot_cells)} cells, {tot_core:.1f} core-hours, "
      f"{tot_core*3600/tot_cells:.1f} s of single-core simulation per cell. The visual "
      f"side needs only the DESDF, "
      + ", ".join(f"{mb(cost['offline'][s]['desdf_bytes'])} MB for {s}" for s in SCENES) + ".\n")

    # -------------------------------------------------------------- per query
    per = {d["scene"]: d for d in cost["online"]["per_scene_ms"]}
    T(r"\begin{table}[t]\centering\small")
    T(rf"\caption{{Time per query, milliseconds, median over "
      rf"{cost['online']['n_queries_per_scene']} held-out queries per scene on one "
      rf"{esc(hw['gpu'])}. The front branch is the cost; everything the acoustic "
      r"term touches is in the (b) rows.}")
    T(r"\label{tab:online}")
    T(r"\begin{tabular}{lllrrr}\toprule")
    T(r"Stage & Branch & & " + " & ".join(esc(s) for s in SCENES) + r" \\\midrule")
    M("\n## Time per query, ms\n")
    M("| stage | branch | device | " + " | ".join(SCENES) + " |")
    M("|---|---|---|" + "---|" * len(SCENES))
    for key, label, dev, br in STAGES:
        vals = [per[s][key] for s in SCENES]
        fmt = [f"{v:.1f}" if v < 10 else f"{v:.0f}" for v in vals]
        T(rf"{label} & {br} & {dev} & " + " & ".join(fmt) + r" \\")
        M(f"| {label.replace('$','').replace(chr(92)+'times','x')} | {br} | {dev} | " + " | ".join(fmt) + " |")
        if key == "vis_encoder" or key == "fusion":
            T(r"\midrule")
    front = [sum(per[s][k] for k in ("image_io", "vis_encoder")) for s in SCENES]
    back_vis = [sum(per[s][k] for k in ("vis_rays", "vis_localize")) for s in SCENES]
    back_ac = [sum(per[s][k] for k in ("ac_io", "ac_feature", "ac_score", "modes", "fusion")) for s in SCENES]
    tot = [per[s]["total"] for s in SCENES]
    T(r"front branch & (f) & & " + " & ".join(f"{v:.0f}" for v in front) + r" \\")
    T(r"back branch, visual & (b) & & " + " & ".join(f"{v:.0f}" for v in back_vis) + r" \\")
    T(r"back branch, added by sound & (b) & & " + " & ".join(f"{v:.0f}" for v in back_ac) + r" \\")
    T(r"\textbf{total} & & & " + " & ".join(rf"\textbf{{{v:.0f}}}" for v in tot) + r" \\")
    T(r"\bottomrule\end{tabular}\end{table}")
    T("")
    M("| **front branch** | (f) | | " + " | ".join(f"{v:.0f}" for v in front) + " |")
    M("| **back branch, visual** | (b) | | " + " | ".join(f"{v:.0f}" for v in back_vis) + " |")
    M("| **back branch, added by sound** | (b) | | " + " | ".join(f"{v:.0f}" for v in back_ac) + " |")
    M("| **total** | | | " + " | ".join(f"**{v:.0f}**" for v in tot) + " |")
    peak = max(per[s]["gpu_peak_mb"] for s in SCENES)
    note = (f"Peak GPU memory {peak/1024:.1f} GB; model load {cost['online']['model_load_s']:.1f} s, once. "
            "Rows are per-stage medians and do not sum to the total row, which is the "
            "median of the whole. Image and impulse-response reads come from network "
            "storage. Scoring here covers every cell of the grid, which is what the "
            "analysis pipeline does to draw the maps; the rule itself needs only the "
            "cells inside its ten half-metre discs, about 800, which the main "
            "repository timed at 1.6 ms.")
    M("\n" + note + "\n")
    T(r"\noindent\footnotesize " + esc(note).replace("%", "\\%"))
    T("")

    # -------------------------------------------------------- scaling with K
    sc = render["scaling"] if "scaling" in render else None
    if sc:
        T(r"\begin{table}[t]\centering\small")
        T(r"\caption{Acoustic scoring against the number of hypotheses. The method "
          r"scores only the discs around $K$ hypotheses, a few percent of the cells "
          r"a cell-wise fusion would score.}")
        T(r"\label{tab:scaling}")
        T(r"\begin{tabular}{rrrr}\toprule")
        T(r"$K$ & Cells scored & Time (ms) & Of a full scan \\\midrule")
        M("\n## Acoustic scoring against the number of hypotheses\n")
        M("| K | cells scored | time | of a full-grid scan |")
        M("|---|---|---|---|")
        for row in sc:
            T(rf"{row['K']} & {row['cells']} & {row['ms']:.2f} & {100*row['fraction']:.1f}\% \\")
            M(f"| {row['K']} | {row['cells']} | {row['ms']:.2f} ms | {100*row['fraction']:.1f}% |")
        T(r"\bottomrule\end{tabular}\end{table}")

    # ------------------------------------- what the acoustic branch could replace
    # Per backbone: the frozen image encoder, the trained head after it (the
    # conv and attention that turn features into rays), and the non-learned
    # floorplan match. The acoustic branch could only ever stand in for the last
    # two, and the table says what that would save and what it would cost.
    bb = {}
    for tag in ("unloc", "f3loc_mono", "disco_rrp"):
        f = DATA / f"backbone_{tag}.json"
        if f.exists():
            bb[tag] = json.loads(f.read_text())
    if bb:
        ac_ms = {s: per[s]["ac_feature"] + per[s]["modes"] + per[s]["fusion"] + 1.6 for s in SCENES}
        T(r"\begin{table}[t]\centering\small")
        T(r"\caption{What the acoustic branch could replace. Each visual backbone is "
          r"a frozen image encoder, a trained head that turns its features into rays, "
          r"and a non-learned match of those rays against the floorplan. Sound can "
          r"stand in only for the last two, and they are a few percent of the "
          r"parameters and of the time; the encoder is the cost. Dropping them "
          r"also drops the hypotheses the acoustic branch ranks, and sound alone "
          r"reaches $36.0\%$ at 1\,m against $60.0\%$ fused (UnLoc, Replica, final protocol). Times are medians "
          r"over the three scenes, milliseconds. UnLoc's checkpoint also carries a "
          r"31\,M-parameter depth head that inference never calls.}")
        T(r"\label{tab:replace}")
        T(r"\begin{tabular}{lrrrrrrrr}\toprule")
        T(r" & \multicolumn{2}{c}{Parameters, M} & \multicolumn{4}{c}{Visual time, ms} & "
          r"\multicolumn{2}{c}{If replaced by sound} \\")
        T(r"\cmidrule(lr){2-3}\cmidrule(lr){4-7}\cmidrule(lr){8-9}")
        T(r"Backbone & encoder & head & encoder & head & match & total & saved ms & acoustic ms \\\midrule")
        M("\n## What the acoustic branch could replace\n")
        M("Each backbone is a frozen image encoder, a trained head that turns features into "
          "rays, and a non-learned match against the floorplan. Sound could stand in only "
          "for the head and the match. Times are medians over the three scenes, ms.\n")
        M("| backbone | encoder (f) params | head (b) params | encoder (f) ms | head (b) ms | match (b) ms | visual total | saved if (b) replaced | acoustic branch ms |")
        M("|---|---|---|---|---|---|---|---|---|")
        for tag, d in bb.items():
            pr = d["params"]
            m = lambda k: float(np.median([r[k] for r in d["per_scene_ms"]]))
            head_ms = m("head") + m("rays")
            match_ms = m("localize")
            saved = head_ms + match_ms
            ac = float(np.median(list(ac_ms.values())))
            T(rf"{esc(d['label'])} & {pr['encoder']/1e6:.1f} & {pr['head']/1e6:.2f} & "
              rf"{m('encoder'):.0f} & {head_ms:.1f} & {match_ms:.1f} & {m('visual_total'):.0f} & "
              rf"{saved:.1f} & {ac:.1f} \\")
            M(f"| {d['label']} | {pr['encoder']/1e6:.1f} M | {pr['head']/1e6:.2f} M | "
              f"{m('encoder'):.0f} | {head_ms:.1f} | {match_ms:.1f} | {m('visual_total'):.0f} | "
              f"{saved:.1f} ms, {pr['head']/1e6:.2f} M | {ac:.1f} |")
        T(r"\bottomrule\end{tabular}\end{table}")
        T("")
        M("\nThe head and the match are 2 to 9% of the parameters and 3 to 30% of the "
          "visual time; the encoder is the cost. They cannot simply be dropped: they are "
          "what produces the hypotheses the acoustic branch ranks, and sound alone reaches "
          "36.0% at 1 m against 60.0% fused (UnLoc, Replica, final protocol). UnLoc's checkpoint also carries a 30.9 M "
          "depth head that inference never calls; deleting it from the file saves 9% of "
          "the parameters at no cost. The acoustic column is the branch's own compute, "
          "with scoring limited to the ten discs (1.6 ms, main repository); reading the "
          "impulse response from network storage adds about 45 ms on this machine.\n")

    TABLES.mkdir(parents=True, exist_ok=True)
    (TABLES / "compute_cost.tex").write_text("\n".join(tex) + "\n")
    (TABLES / "compute_cost.md").write_text("\n".join(md) + "\n")
    print("wrote tables/compute_cost.tex and tables/compute_cost.md")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
