#!/usr/bin/env python3
"""The Replica main table under the protocol the paper actually reports.

paper_artifacts.py builds tab_main on the motion-collection split, which is
what the paper used before the split was found to leak acoustic evidence
(Sec. supp-split). The headline protocol is now pooled collections with rooms
held out, and room_cv_eval.py holds those numbers. This reads its JSON and
writes them in the main table's layout, so experiments.tex can \\input one file
that agrees with the prose.

    python scripts/room_cv_table.py
"""
from __future__ import annotations
import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SRC = REPO_ROOT / "outputs" / "metrics" / "room_cv.json"
OUT = REPO_ROOT / "docs" / "tables" / "tab_main_roomcv.tex"
ORDER = [("f3STFT", "F3Loc mono"), ("unlocSTFT", "UnLoc"), ("discoID", "DisCo-FLoc RRP")]
TH = ["0.1m", "0.5m", "1.0m", "2.0m", "5.0m"]

d = json.loads(SRC.read_text())["results"]
tex = [r"\begin{table}[t]\centering\small",
       r"\caption{Single-frame localization on Replica, recall (\%). Queries are "
       r"furnished recordings matched against floorplan-rendered candidates. Both "
       r"motion collections are pooled and whole rooms are held out: the four "
       r"scalars are refit on two rooms and reported on the third, rotating, so no "
       r"reported query comes from a room its scalars saw. Gains carry paired "
       r"bootstrap intervals over queries; the room-clustered intervals, which are "
       r"wider and span zero at three rooms, are in Tab.~\ref{tab:cluster}.}",
       r"\label{tab:main_roomcv}",
       r"\begin{tabular}{llccccccc}\toprule",
       r"Backbone & Acoustic & $0.1$\,m & $0.5$\,m & $1$\,m & $2$\,m & $5$\,m & Median & $\Delta_{1\mathrm{m}}$ \\\midrule"]
n = None
for tag, label in ORDER:
    if tag not in d:
        continue
    r = d[tag]; n = r["n"]
    v = r["vision_recalls"]; o = r["recalls"]
    lo, hi = 100 * r["ci"][0], 100 * r["ci"][1]
    bold = lo > 0
    bb = (lambda x: rf"\textbf{{{x}}}") if bold else (lambda x: x)
    tex.append(rf"\multirow{{2}}{{*}}{{{label}}} & $\times$ & "
               + " & ".join(f"{100*v[t]:.1f}" for t in TH)
               + rf" & {r['vision_median']:.2f} & -- \\")
    med = f"{r['median']:.2f}"
    cells = [bb(f"{100*o[t]:.1f}") for t in TH] + [bb(med)]
    gain = bb(f"{100*r['gain']:+.1f}") + rf"\,{{\scriptsize[{lo:+.1f},{hi:+.1f}]}}"
    tex.append(r"& $\checkmark$ & " + " & ".join(cells) + rf" & {gain} \\")
    tex.append(r"\midrule")
tex[-1] = r"\bottomrule"
tex += [r"\end{tabular}", rf"\\[2pt]\footnotesize {n} queries over three rooms per backbone; "
        r"bold where the interval excludes zero.", r"\end{table}"]
OUT.write_text("% Generated by scripts/room_cv_table.py from outputs/metrics/room_cv.json -- do not edit.\n"
               + "\n".join(tex) + "\n")
print(f"wrote {OUT}")
