#!/usr/bin/env python3
"""The paper's main table and the projection-transfer table, from the JSON the
selection scripts wrote. Cells whose run has not finished are printed as
\\emph{tbd} so the table is never silently stale.

    tab_main_val.tex    per benchmark and backbone: vision alone, and the
                        configuration chosen on validation rooms evaluated once
                        on the test rooms, with what was chosen
    tab_projection.tex  where the projection was trained against where it is
                        used, test-room CV, gain at 1 m

    python scripts/val_tables.py
"""

from __future__ import annotations

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
RES = REPO_ROOT / "feasible" / "results"
OUT = REPO_ROOT / "docs" / "tables"
TBD = r"\emph{tbd}"
BB = [("f3loc", "F3Loc mono"), ("unloc", "UnLoc"), ("disco", "DisCo-FLoc RRP")]
DS = [("replica", "Replica", "furnished"), ("mp3d", "Matterport3D", "furnished"),
      ("s3d", "Structured3D", "matched")]
TH = ["0.1m", "0.5m", "1.0m", "2.0m", "5.0m"]


def load(p: Path):
    return json.loads(p.read_text()) if p.exists() else None


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    # ------------------------------------------------------------- main
    L = []
    L.append(r"\begin{table*}[t]\centering\small")
    L.append(r"\caption{Single-frame localization, recall (\%). One method throughout: the "
             r"projection is trained on the benchmark's own training rooms (Structured3D, which "
             r"has no furnished recordings, uses the pooled projection), a hypothesis is "
             r"summarised by the visual log-posterior at its centre and the $0.9$ quantile of "
             r"the acoustic score over its disc, and the rule has three scalars. Only those three "
             r"scalars are chosen per backbone, on validation rooms, by recall at $1$\,m; the test "
             r"rooms are evaluated once and nothing is refit on them. Query recordings are "
             r"furnished except on Structured3D. Gains carry paired bootstrap intervals over queries.}")
    L.append(r"\label{tab:main_val}")
    L.append(r"\begin{tabular}{llcccccccl}\toprule")
    L.append(r"Benchmark & Backbone & Audio & $0.1$\,m & $0.5$\,m & $1$\,m & $2$\,m & $5$\,m & "
             r"Median & $\Delta_{1\mathrm{m}}$ [95\% CI] \\\midrule")
    for key, name, _ in DS:
        j = load(RES / f"VAL_{key}_fixed_indomain.json")
        for i, (bb, label) in enumerate(BB):
            r = (j or {}).get("results", {}).get(bb, {}).get("selected")
            first = rf"\multirow{{{2*len(BB)}}}{{*}}{{{name}}} " if i == 0 else ""
            if not r or "vision" not in r:
                L.append(rf"{first}& \multirow{{2}}{{*}}{{{label}}} & $\times$ & {TBD} & & & & & & \\")
                L.append(rf"& & $\checkmark$ & {TBD} & & & & & & \\")
            else:
                v = [100 * r["vision_recalls"][t] for t in TH]
                o = [100 * r["recalls"][t] for t in TH]
                L.append(rf"{first}& \multirow{{2}}{{*}}{{{label}}} & $\times$ & "
                         + " & ".join(f"{x:.1f}" for x in v) + rf" & {r['vision_median']:.2f} & -- \\")
                g, (lo, hi) = 100 * r["gain"], (100 * r["ci"][0], 100 * r["ci"][1])
                src = r["source"] or "none"
                L.append(rf"& & $\checkmark$ & " + " & ".join(rf"\textbf{{{x:.1f}}}" for x in o)
                         + rf" & \textbf{{{r['median']:.2f}}} & \textbf{{{g:+.1f}}}\,{{\scriptsize[{lo:+.1f},{hi:+.1f}]}} \\")
            if i < len(BB) - 1:
                L.append(r"\cmidrule(lr){2-10}")
        L.append(r"\midrule")
    L[-1] = r"\bottomrule\end{tabular}\end{table*}"
    (OUT / "tab_main_val.tex").write_text(
        "% Generated by scripts/val_tables.py from feasible/results/VAL_*.json -- do not edit by hand.\n"
        + "\n".join(L) + "\n")

    # --------------------------------------------------------- protocol
    Q = []
    Q.append(r"\begin{table}[t]\centering\small")
    Q.append(r"\caption{Gain at $1$\,m on the test rooms under four ways of fixing the method, each "
             r"with its scalars chosen on validation rooms. \emph{none}: no projection. "
             r"\emph{own}: projection trained on the benchmark's training rooms (pooled for "
             r"Structured3D). \emph{pooled}: one projection trained on Replica and Matterport3D "
             r"together, deployed everywhere. \emph{searched}: source, summaries and rule also "
             r"chosen on validation, the most flexible protocol and not the one we report.}")
    Q.append(r"\label{tab:protocol}")
    Q.append(r"\begin{tabular}{llcccc}\toprule")
    Q.append(r"Benchmark & Backbone & none & own $W$ & pooled $W$ & searched \\\midrule")
    for key, name, _ in DS:
        own = load(RES / f"VAL_{key}_fixed_indomain.json")
        pooled = load(RES / f"VAL_{key}_fixed_B.json")
        searched = load(RES / f"VAL_{key}.json")
        for i, (bb, label) in enumerate(BB):
            def g(j, variant):
                r = (j or {}).get("results", {}).get(bb, {}).get(variant)
                return f"{100*r['gain']:+.1f}" if r and "gain" in r else TBD
            cells = [g(own, "no projection"), g(own, "selected"), g(pooled, "selected"),
                     g(searched, "selected")]
            first = rf"\multirow{{{len(BB)}}}{{*}}{{{name}}} " if i == 0 else ""
            Q.append(rf"{first}& {label} & " + " & ".join(cells) + r" \\")
        Q.append(r"\midrule")
    Q[-1] = r"\bottomrule\end{tabular}\end{table}"
    (OUT / "tab_protocol.tex").write_text(
        "% Generated by scripts/val_tables.py from feasible/results/VAL_*.json -- do not edit by hand.\n"
        + "\n".join(Q) + "\n")

    # ------------------------------------------------------- projection
    P = []
    P.append(r"\begin{table}[t]\centering\small")
    P.append(r"\caption{Where the acoustic projection $W$ is trained against where it is used. Gain "
             r"at $1$\,m over the visual backbone, test rooms held out by room, three scalars "
             r"refit per fold. R: Replica training rooms; M: Matterport3D training rooms; B: both; "
             r"T: both plus Structured3D, whose recordings have no furnished twin and enter as "
             r"self-pairs. Structured3D has no furniture gap, so $W$ has nothing to close there.}")
    P.append(r"\label{tab:projection}")
    P.append(r"\begin{tabular}{llccccc}\toprule")
    P.append(r"Benchmark & Backbone & none & R & M & B & T \\\midrule")
    import sys
    sys.path.insert(0, str(REPO_ROOT / "feasible"))
    from run_projection_matrix import IDENT, tag_of
    for key, name, _ in DS:
        j = load(RES / f"P_matrix_{key}.json")
        res = (j or {}).get("results", {})
        for i, (bb, label) in enumerate(BB):
            cells = []
            for src in (None, "R", "M", "B", "T"):
                tag = IDENT[(key, bb)] if src is None else tag_of(key, bb, src)
                r = res.get(tag)
                cells.append(f"{100*r['gain']:+.1f}" if r else TBD)
            best = max((float(c) for c in cells if c != TBD), default=None)
            cells = [rf"\textbf{{{c}}}" if best is not None and c != TBD and float(c) == best else c
                     for c in cells]
            first = rf"\multirow{{{len(BB)}}}{{*}}{{{name}}} " if i == 0 else ""
            P.append(rf"{first}& {label} & " + " & ".join(cells) + r" \\")
        P.append(r"\midrule")
    P[-1] = r"\bottomrule\end{tabular}\end{table}"
    (OUT / "tab_projection.tex").write_text(
        "% Generated by scripts/val_tables.py from feasible/results/P_matrix_*.json -- do not edit by hand.\n"
        + "\n".join(P) + "\n")
    print("wrote", OUT / "tab_main_val.tex", OUT / "tab_protocol.tex", "and", OUT / "tab_projection.tex")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
